import { useState, useEffect } from 'react';
import { DndProvider, useDrag, useDrop } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';
import { ChevronLeft, Plus, Calendar, User, AlertCircle, Paperclip, MessageSquare, X, Sparkles } from 'lucide-react';
import { mockActivities } from './mockData';
import { Activity, ActivityStatus, Priority, ObraConstrucao, AcaoUnidade } from './types';
import { getActivities, saveActivities } from './Kanban';
import { selecionarTemplateAutomatico, calcularPrazo, TaskTemplate } from './kanbanTemplates';

interface KanbanBoardProps {
  planId: string;
  itemId: string;
  itemType: 'obra' | 'acao-unidade';
  itemData: ObraConstrucao | AcaoUnidade;
  onBack: () => void;
}

const ItemTypes = {
  CARD: 'card'
};

interface DragItem {
  id: string;
  status: ActivityStatus;
}

function ActivityCard({ activity, onMove }: { activity: Activity; onMove: (id: string, newStatus: ActivityStatus) => void }) {
  const [{ isDragging }, drag] = useDrag(() => ({
    type: ItemTypes.CARD,
    item: { id: activity.id, status: activity.status },
    collect: (monitor) => ({
      isDragging: monitor.isDragging(),
    }),
  }));

  const getPriorityColor = (priority: Priority) => {
    switch (priority) {
      case 'Alta': return 'bg-red-500';
      case 'Média': return 'bg-yellow-500';
      case 'Baixa': return 'bg-green-500';
    }
  };

  const isOverdue = new Date(activity.deadline) < new Date() && activity.status !== 'FEITO';

  return (
    <div
      ref={drag as any}
      className={`bg-white rounded-lg shadow-md p-4 mb-3 cursor-move hover:shadow-lg transition-all ${
        isDragging ? 'opacity-50' : 'opacity-100'
      }`}
    >
      <div className="flex items-start justify-between mb-3">
        <div className="flex-1">
          <h4 className="font-semibold text-slate-800">{activity.name}</h4>
          {activity.category && (
            <span className="text-xs text-slate-500 mt-1 inline-block">{activity.category}</span>
          )}
        </div>
        <div className="flex items-center gap-2 ml-2">
          <div className={`w-2 h-2 rounded-full ${getPriorityColor(activity.priority)} flex-shrink-0`} />
          {activity.autoGenerated && (
            <span title="Tarefa gerada automaticamente"><Sparkles className="w-3 h-3 text-blue-500" /></span>
          )}
        </div>
      </div>

      <p className="text-sm text-slate-600 mb-3 line-clamp-2">{activity.description}</p>

      <div className="space-y-2 mb-3">
        <div className="flex items-center gap-2 text-xs text-slate-500">
          <User className="w-3 h-3" />
          <span>{activity.responsible}</span>
        </div>
        <div className="flex items-center gap-2 text-xs text-slate-500">
          <Calendar className="w-3 h-3" />
          <span>{new Date(activity.deadline).toLocaleDateString('pt-BR')}</span>
          {isOverdue && (
            <span className="flex items-center gap-1 text-red-600 font-semibold">
              <AlertCircle className="w-3 h-3" />
              Atrasada
            </span>
          )}
        </div>
      </div>

      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <span className={`px-2 py-1 text-xs rounded-full font-semibold ${
            activity.priority === 'Alta' ? 'bg-red-100 text-red-700' :
            activity.priority === 'Média' ? 'bg-yellow-100 text-yellow-700' :
            'bg-green-100 text-green-700'
          }`}>
            {activity.priority}
          </span>
          {activity.tags && activity.tags.map(tag => (
            <span key={tag} className="px-2 py-1 text-xs rounded-full bg-slate-100 text-slate-600">
              {tag}
            </span>
          ))}
        </div>
        <div className="flex items-center gap-2 text-slate-400">
          {activity.comments.length > 0 && (
            <div className="flex items-center gap-1">
              <MessageSquare className="w-4 h-4" />
              <span className="text-xs">{activity.comments.length}</span>
            </div>
          )}
          {activity.attachments.length > 0 && (
            <div className="flex items-center gap-1">
              <Paperclip className="w-4 h-4" />
              <span className="text-xs">{activity.attachments.length}</span>
            </div>
          )}
        </div>
      </div>

      {activity.percentage > 0 && activity.status !== 'FEITO' && (
        <div className="mt-3">
          <div className="flex items-center justify-between mb-1">
            <span className="text-xs text-slate-600">Progresso</span>
            <span className="text-xs font-semibold text-slate-700">{activity.percentage}%</span>
          </div>
          <div className="w-full bg-slate-200 rounded-full h-1.5">
            <div
              className="bg-blue-500 h-1.5 rounded-full transition-all"
              style={{ width: `${activity.percentage}%` }}
            />
          </div>
        </div>
      )}
    </div>
  );
}

function Column({ title, status, activities, onMove, onAddActivity }: {
  title: string;
  status: ActivityStatus;
  activities: Activity[];
  onMove: (id: string, newStatus: ActivityStatus) => void;
  onAddActivity: (status: ActivityStatus) => void;
}) {
  const [{ isOver }, drop] = useDrop(() => ({
    accept: ItemTypes.CARD,
    drop: (item: DragItem) => {
      if (item.status !== status) {
        onMove(item.id, status);
      }
    },
    collect: (monitor) => ({
      isOver: monitor.isOver(),
    }),
  }));

  const getColumnColor = () => {
    switch (status) {
      case 'A FAZER': return 'border-slate-300 bg-slate-50';
      case 'FAZENDO': return 'border-blue-300 bg-blue-50';
      case 'FEITO': return 'border-green-300 bg-green-50';
    }
  };

  return (
    <div className="flex-1 min-w-[320px]">
      <div className={`rounded-lg border-2 ${getColumnColor()} ${isOver ? 'ring-4 ring-blue-200' : ''} transition-all`}>
        <div className="p-4 border-b border-slate-200">
          <div className="flex items-center justify-between mb-2">
            <h3 className="font-bold text-slate-800 text-lg">{title}</h3>
            <span className="bg-slate-200 text-slate-700 px-2 py-1 rounded-full text-sm font-semibold">
              {activities.length}
            </span>
          </div>
          <button
            onClick={() => onAddActivity(status)}
            className="w-full flex items-center justify-center gap-2 text-slate-600 hover:text-slate-900 hover:bg-white py-2 rounded-lg transition-colors"
          >
            <Plus className="w-4 h-4" />
            <span className="text-sm font-semibold">Nova Atividade</span>
          </button>
        </div>
        <div ref={drop as any} className="p-4 min-h-[600px]">
          {activities.map(activity => (
            <ActivityCard key={activity.id} activity={activity} onMove={onMove} />
          ))}
        </div>
      </div>
    </div>
  );
}

function NewActivityModal({ isOpen, onClose, onCreate, initialStatus, planId, itemId, itemType }: {
  isOpen: boolean;
  onClose: () => void;
  onCreate: (activity: Partial<Activity>) => void;
  initialStatus: ActivityStatus;
  planId: string;
  itemId: string;
  itemType: 'obra' | 'acao-unidade';
}) {
  const [nome, setNome] = useState('');
  const [descricao, setDescricao] = useState('');
  const [categoria, setCategoria] = useState('');
  const [responsavel, setResponsavel] = useState('');
  const [prioridade, setPrioridade] = useState<Priority>('Média');
  const [dataInicio, setDataInicio] = useState('');
  const [prazo, setPrazo] = useState('');

  const handleSubmit = () => {
    onCreate({
      planId,
      itemId,
      itemType,
      name: nome,
      description: descricao,
      category: categoria,
      responsible: responsavel,
      priority: prioridade,
      startDate: dataInicio,
      deadline: prazo,
      status: initialStatus,
      percentage: 0,
      autoGenerated: false,
      comments: [],
      attachments: [],
      history: [],
      tags: [],
    });

    // Reset form
    setNome('');
    setDescricao('');
    setCategoria('');
    setResponsavel('');
    setPrioridade('Média');
    setDataInicio('');
    setPrazo('');
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6 border-b border-slate-200 flex items-center justify-between sticky top-0 bg-white">
          <h2 className="text-2xl font-bold text-slate-800">Nova Atividade</h2>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 transition-colors">
            <X className="w-6 h-6" />
          </button>
        </div>

        <div className="p-6 space-y-4">
          <div>
            <label className="block text-sm font-semibold text-slate-700 mb-2">Nome da Atividade *</label>
            <input
              type="text"
              value={nome}
              onChange={(e) => setNome(e.target.value)}
              className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              placeholder="Ex: Instalações hidráulicas"
            />
          </div>

          <div>
            <label className="block text-sm font-semibold text-slate-700 mb-2">Descrição</label>
            <textarea
              value={descricao}
              onChange={(e) => setDescricao(e.target.value)}
              className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none resize-none"
              rows={4}
              placeholder="Descreva os detalhes da atividade..."
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">Categoria</label>
              <input
                type="text"
                value={categoria}
                onChange={(e) => setCategoria(e.target.value)}
                className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                placeholder="Ex: Execução, Projeto"
              />
            </div>

            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">Responsável *</label>
              <input
                type="text"
                value={responsavel}
                onChange={(e) => setResponsavel(e.target.value)}
                className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                placeholder="Nome do responsável"
              />
            </div>
          </div>

          <div>
            <label className="block text-sm font-semibold text-slate-700 mb-2">Prioridade</label>
            <select
              value={prioridade}
              onChange={(e) => setPrioridade(e.target.value as Priority)}
              className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
            >
              <option value="Baixa">Baixa</option>
              <option value="Média">Média</option>
              <option value="Alta">Alta</option>
            </select>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">Data de Início</label>
              <input
                type="date"
                value={dataInicio}
                onChange={(e) => setDataInicio(e.target.value)}
                className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              />
            </div>

            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">Prazo *</label>
              <input
                type="date"
                value={prazo}
                onChange={(e) => setPrazo(e.target.value)}
                className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              />
            </div>
          </div>
        </div>

        <div className="p-6 border-t border-slate-200 flex gap-3">
          <button
            onClick={onClose}
            className="flex-1 px-4 py-3 bg-slate-200 text-slate-700 rounded-lg font-semibold hover:bg-slate-300 transition-colors"
          >
            Cancelar
          </button>
          <button
            onClick={handleSubmit}
            disabled={!nome || !responsavel || !prazo}
            className="flex-1 px-4 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Criar Atividade
          </button>
        </div>
      </div>
    </div>
  );
}

export default function KanbanBoard({ planId, itemId, itemType, itemData, onBack }: KanbanBoardProps) {
  const [allActivities, setAllActivities] = useState<Activity[]>(() => getActivities());
  const [modalOpen, setModalOpen] = useState(false);
  const [modalStatus, setModalStatus] = useState<ActivityStatus>('A FAZER');
  const [initialized, setInitialized] = useState(false);

  const activities = allActivities.filter(
    a => a.planId === planId && a.itemId === itemId && a.itemType === itemType
  );

  // Carregar ou gerar atividades
  useEffect(() => {
    if (activities.length > 0) {
      setInitialized(true);
    } else {
      setInitialized(false);
    }
  }, [activities.length]);

  // Função para gerar tarefas do template
  const gerarTarefasDoTemplate = (tarefas: TaskTemplate[]) => {
    const dataInicio = itemType === 'obra'
      ? (itemData as ObraConstrucao).previsaoConclusao
      : new Date().toISOString().split('T')[0];

    const novasAtividades: Activity[] = tarefas.map((t, idx) => ({
      id: `${itemId}-task-${idx}`,
      schoolId: '', // legacy
      planId,
      itemId,
      itemType,
      name: t.nome,
      description: t.descricao,
      category: t.categoria,
      responsible: t.responsavel || 'A definir',
      priority: t.prioridade,
      deadline: calcularPrazo(dataInicio, t.prazoEmDias),
      startDate: dataInicio,
      percentage: 0,
      status: 'A FAZER',
      autoGenerated: true,
      comments: [],
      attachments: [],
      history: [],
      tags: [itemType === 'obra' ? (itemData as ObraConstrucao).tipo : (itemData as AcaoUnidade).tipo],
    }));

    setAllActivities(prev => {
      const updated = [...prev, ...novasAtividades];
      saveActivities(updated);
      return updated;
    });
    setInitialized(true);
  };

  const handleMove = (activityId: string, newStatus: ActivityStatus) => {
    setAllActivities(prev => {
      const updated = prev.map(activity =>
        activity.id === activityId
          ? { ...activity, status: newStatus, percentage: newStatus === 'FEITO' ? 100 : activity.percentage }
          : activity
      );
      saveActivities(updated);
      return updated;
    });
  };

  const handleAddActivity = (status: ActivityStatus) => {
    setModalStatus(status);
    setModalOpen(true);
  };

  const handleCreateActivity = (newActivity: Partial<Activity>) => {
    const activity: Activity = {
      id: `${itemId}-custom-${Date.now()}`,
      schoolId: '',
      ...newActivity,
    } as Activity;

    setAllActivities(prev => {
      const updated = [...prev, activity];
      saveActivities(updated);
      return updated;
    });
  };

  const todoActivities = activities.filter(a => a.status === 'A FAZER');
  const doingActivities = activities.filter(a => a.status === 'FAZENDO');
  const doneActivities = activities.filter(a => a.status === 'FEITO');

  const overallProgress = activities.length > 0
    ? Math.round((doneActivities.length / activities.length) * 100)
    : 0;

  // Determinar o nome do item
  const itemName = itemType === 'obra'
    ? (itemData as ObraConstrucao).nome
    : `${(itemData as AcaoUnidade).tipo === 'adaptacao' ? 'Adaptação' : 'Ampliação'} - Unidade`;

  const itemLocation = itemType === 'obra'
    ? `${(itemData as ObraConstrucao).bairro}, ${(itemData as ObraConstrucao).setor}`
    : '';

  // Se não inicializado, mostrar tela de seleção de template
  if (!initialized) {
    const tipoItem = itemType === 'obra'
      ? (itemData as ObraConstrucao).tipo
      : (itemData as AcaoUnidade).tipo;

    const template = selecionarTemplateAutomatico(itemType, tipoItem);

    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 p-8">
        <button
          onClick={onBack}
          className="flex items-center gap-2 text-slate-600 hover:text-slate-900 mb-6 transition-colors"
        >
          <ChevronLeft className="w-5 h-5" />
          Voltar
        </button>

        <div className="max-w-3xl mx-auto">
          <div className="bg-white rounded-2xl shadow-lg p-8">
            <div className="text-center mb-6">
              <Sparkles className="w-12 h-12 text-blue-500 mx-auto mb-4" />
              <h1 className="text-3xl font-bold text-slate-800 mb-2">Configurar Kanban</h1>
              <p className="text-slate-600">{itemName}</p>
              {itemLocation && <p className="text-sm text-slate-500">{itemLocation}</p>}
            </div>

            <div className="bg-blue-50 border-2 border-blue-200 rounded-xl p-6 mb-6">
              <h3 className="font-bold text-blue-900 mb-2">Template Recomendado</h3>
              <p className="text-lg font-semibold text-blue-800 mb-1">{template.nome}</p>
              <p className="text-sm text-blue-700 mb-4">{template.descricao}</p>

              <div className="bg-white rounded-lg p-4">
                <p className="text-sm font-semibold text-slate-700 mb-2">
                  📋 Serão criadas {template.tarefas.length} tarefas automaticamente
                </p>
                <div className="grid grid-cols-2 gap-2 text-xs text-slate-600">
                  {Array.from(new Set(template.tarefas.map(t => t.categoria))).map(cat => {
                    const count = template.tarefas.filter(t => t.categoria === cat).length;
                    return (
                      <div key={cat} className="flex items-center gap-2">
                        <div className="w-2 h-2 rounded-full bg-blue-500" />
                        <span>{cat} ({count})</span>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>

            <div className="flex gap-3">
              <button
                onClick={onBack}
                className="flex-1 px-6 py-3 bg-slate-200 text-slate-700 rounded-xl font-semibold hover:bg-slate-300 transition-colors"
              >
                Cancelar
              </button>
              <button
                onClick={() => gerarTarefasDoTemplate(template.tarefas)}
                className="flex-1 px-6 py-3 bg-blue-600 text-white rounded-xl font-semibold hover:bg-blue-700 transition-colors shadow-lg"
              >
                Criar Kanban com Template
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <DndProvider backend={HTML5Backend}>
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
        <div className="p-8">
          <button
            onClick={onBack}
            className="flex items-center gap-2 text-slate-600 hover:text-slate-900 mb-6 transition-colors"
          >
            <ChevronLeft className="w-5 h-5" />
            Voltar
          </button>

          <div className="bg-white rounded-2xl shadow-lg p-6 mb-8">
            <div className="flex items-start justify-between mb-6">
              <div>
                <h1 className="text-3xl font-bold text-slate-800 mb-2">{itemName}</h1>
                {itemLocation && <p className="text-slate-600">{itemLocation}</p>}
                <p className="text-sm text-slate-500 mt-1">
                  {itemType === 'obra' ? 'Obra de Construção' : 'Ação em Unidade Existente'}
                </p>
              </div>
              <div className="text-right">
                <div className="text-4xl font-bold text-blue-600 mb-1">{overallProgress}%</div>
                <div className="text-sm text-slate-600">Concluído</div>
              </div>
            </div>

            <div className="mb-4">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-semibold text-slate-700">Progresso Geral</span>
                <span className="text-sm text-slate-600">
                  {doneActivities.length} de {activities.length} atividades concluídas
                </span>
              </div>
              <div className="w-full bg-slate-200 rounded-full h-4 overflow-hidden">
                <div
                  className="h-full bg-gradient-to-r from-blue-500 to-green-500 transition-all duration-500 rounded-full"
                  style={{ width: `${overallProgress}%` }}
                />
              </div>
            </div>

            <div className="grid grid-cols-3 gap-4 text-center">
              <div className="bg-slate-50 rounded-lg p-3">
                <div className="text-2xl font-bold text-slate-700">{todoActivities.length}</div>
                <div className="text-sm text-slate-600">A Fazer</div>
              </div>
              <div className="bg-blue-50 rounded-lg p-3">
                <div className="text-2xl font-bold text-blue-700">{doingActivities.length}</div>
                <div className="text-sm text-slate-600">Em Andamento</div>
              </div>
              <div className="bg-green-50 rounded-lg p-3">
                <div className="text-2xl font-bold text-green-700">{doneActivities.length}</div>
                <div className="text-sm text-slate-600">Concluídas</div>
              </div>
            </div>
          </div>

          <div className="flex gap-6 overflow-x-auto pb-4">
            <Column
              title="A FAZER"
              status="A FAZER"
              activities={todoActivities}
              onMove={handleMove}
              onAddActivity={handleAddActivity}
            />
            <Column
              title="FAZENDO"
              status="FAZENDO"
              activities={doingActivities}
              onMove={handleMove}
              onAddActivity={handleAddActivity}
            />
            <Column
              title="FEITO"
              status="FEITO"
              activities={doneActivities}
              onMove={handleMove}
              onAddActivity={handleAddActivity}
            />
          </div>
        </div>

        <NewActivityModal
          isOpen={modalOpen}
          onClose={() => setModalOpen(false)}
          onCreate={handleCreateActivity}
          initialStatus={modalStatus}
          planId={planId}
          itemId={itemId}
          itemType={itemType}
        />
      </div>
    </DndProvider>
  );
}
